### ISSUE TITLE
大佬 使用魔百盒创建失败啊

### ISSUE THREAD

**Issue by DieRose** [leosam1024/tvbox-mv#3]
容器无法启动 日志是exec format error
芯片是s905l3a arm64的 隔壁xiaoya-tvbox也出现过这种问题 大佬可以参考下

**Comment by leosam1024** [comment]
你直接装个java17的环境，启动一下jar试试？

**Comment by leosam1024** [comment]
原因是：
Docker镜像是为x86架构构建的，而你正试图在ARM架构的机器上运行它。
这就是产生“exec format error”的原因。

有时间可以弄个arm版的镜像

```
# 使用一个仅包含JRE 11的运行时镜像
FROM arm64v8/openjdk:11-jre-slim

# 设置工作目录
WORKDIR /app

# 从构建镜像中复制打包好的jar文件到运行镜像中
COPY --from=build /app/target/tvbox-mv-0.0.1-SNAPSHOT.jar /app/tvbox-mv-0.0.1-SNAPSHOT.jar

# 暴露端口
EXPOSE 7777

# 运行应用程序
CMD ["java", "-jar", "tvbox-mv-0.0.1-SNAPSHOT.jar"]

```

**Comment by DieRose** [comment]
> 原因是： Docker镜像是为x86架构构建的，而你正试图在ARM架构的机器上运行它。 这就是产生“exec format error”的原因。
> 
> 有时间可以弄个arm版的镜像
> 
> ```
> # 使用一个仅包含JRE 11的运行时镜像
> FROM arm64v8/openjdk:11-jre-slim
> 
> # 设置工作目录
> WORKDIR /app
> 
> # 从构建镜像中复制打包好的jar文件到运行镜像中
> COPY --from=build /app/target/tvbox-mv-0.0.1-SNAPSHOT.jar /app/tvbox-mv-0.0.1-SNAPSHOT.jar
> 
> # 暴露端口
> EXPOSE 7777
> 
> # 运行应用程序
> CMD ["java", "-jar", "tvbox-mv-0.0.1-SNAPSHOT.jar"]
> ```

好的感谢
